[project]
name = "enduro_app_admin"
description = "Enduro challenges admin"

dependencies = [
    "django>=5.2",
    "django-split-settings>=1.3",
    "django-environ>=0.12",
    "psycopg2-binary>=2.9",
    "django-stubs>=5.2",
    "django-storages>=1.14",
    "django-object-actions>=5.0",
    "structlog>=25.5",
    "types-python-dateutil>=2.9",
    "tenacity>=9.1",
    "types-requests>=2.32",
    "requests>=2.32",
    "django-admin-inline-paginator>=0.4.0",
    "django-admin-extra-buttons>=1.6.0",
    "django-admin-rangefilter>=0.13.2",
    "django-clickhouse-backend>=1.3.2",
    "django-admin-list-filters>=1.3.1",
    "django-import-export>=3.3.9",
]

[dependency-groups]
dev = [
    "nplusone>=1.0",
    "django-debug-toolbar>=5.2",
    "django-querycount>=0.8",
    "pytest-django>=4.11",
    "django-webtest>=1.9",
]

[tool.ruff]
[tool.ruff.lint.per-file-ignores]
"app/tests/*" = ["S101", "PLR2004", "PLR0913"]

[tool.mypy]
exclude = [
    ".venv",
]